---
- name: provision a pbs node
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: create HPC pbsadmin user
      user:
        name: pbsadmin
        state: present
        shell: /bin/bash
        password: "{{ 'Password!' | password_hash('sha512') }}"
        update_password: on_create
    - name: modify sshd_config to allow password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        insertafter: '#PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: restart_sshd
    - name: sudo
      copy:
        dest: /etc/sudoers.d/pbsadmin
        content: "pbsadmin ALL=(root) NOPASSWD: ALL"
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted